### PR TITLE
Fix: Refetch reference after raising file reference expired exception

### PR DESCRIPTION
**Pull request by Lqlsoftware**
This fix works for handling the FILE_REFERENCE_EXPIRED exception.
The script will try 3 times to refetch the reference which is expired before XD.

### CODE REVIEW

**Comment by Dineshkarthik** [comment]
@Lqlsoftware are you working on fixing the code coverage?
If not I can pull in your changes and write required unit-tests and create a new PR which supersedes this one.

**Comment by Lqlsoftware** [comment]
@Dineshkarthik Sorry, I was doing something else today.
The low code coverage is caused by `except` of 400-request exception, `client.get_messages()`, `log. warning()` and `log.error()` which is not include in current unit-tests.
I have done several tests on those methods and exceptions, which shows that they worked as we excepted.

**Comment by Dineshkarthik** [comment]
@Lqlsoftware I have cherry-picked your changes and added few more changes along with unit-test to increase code-coverage in PR #63 
If you are okay with the other PR we can close this and merge the other one.

**Comment by Lqlsoftware** [comment]
Ok! I will close this pr. Great work, man.

**Pull request closed without merging**
